/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_oop;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Class NameFram tao cua so nhap ten Bang cong viec hoac ten ToDoList
 * @author nhom2
 */
public class NameFrame extends javax.swing.JFrame {

    /**
     * Creates new form nameFrame
     */
    public NameFrame(JFrame mainFrame, String s, String txt, String action) {
        this.mainFrame = mainFrame;
        initComponents();
        this.setLocation(500, 300);
        lbTitle.setText(s);
        tfName.setText(txt);
        tfName.selectAll();
        btCreate.setText(action);
    }
    public NameFrame(JFrame mainFrame, String s, String txt, String action,boolean b) {
        this.mainFrame = mainFrame;
        initComponents();
        this.setLocation(500, 300);
        lbTitle.setText(s);
        tfName.setText(txt);
        tfName.selectAll();
        btCreate.setText(action);
        this.create = b;
    }

    public JFrame getMainFrame() {
        return mainFrame;
    }

    public void setMainFrame(JFrame mainFrame) {
        this.mainFrame = mainFrame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btCreate.setText("Create");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        tfName.requestFocus();
        String sName  = tfName.getText(); 
        if(sName.equals("")){ 
            JOptionPane.showMessageDialog(rootPane, "Please enter your board name", "Error", HEIGHT);
            return;
        }
        boolean b = true;
        if(mainFrame instanceof BoardFrame){
            BoardFrame bf = (BoardFrame) mainFrame;
            b = bf.getData(sName);
            if(!b) 
                JOptionPane.showMessageDialog(rootPane, "Board is existed", "Error", HEIGHT);
            else{
                this.setVisible(false);
            }
        }else if(mainFrame instanceof DetailJFrame){
            DetailJFrame df = (DetailJFrame) mainFrame;
            if(create)
                b = df.getData(sName);
            else b = df.getNewName(sName);
            if(!b) 
                JOptionPane.showMessageDialog(rootPane, "Name is existed", "Error", HEIGHT);
            else{
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_btCreateActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tfName.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(mainFrame instanceof BoardFrame){ 
            BoardFrame bf = (BoardFrame) mainFrame;
            bf.end();
        }else if(mainFrame instanceof DetailJFrame){
            DetailJFrame df = (DetailJFrame) mainFrame;
            df.end();
        }
            
        
    }//GEN-LAST:event_formWindowClosing

    private JFrame mainFrame;
    private boolean create;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
