/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_oop;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Thong Bao mot Task den thoi gian bat dau
 * @author nhom2
 */
public class NotificationFrame extends javax.swing.JFrame {

  
    /**
     * Creates new form NotificationFrame
     */
    public NotificationFrame() {
        initComponents();
    }

    public NotificationFrame(String ssound,Thread thr,String information) {
        initComponents();
        taIonformation.setText(information);
        this.sound = new MakeSound(ssound);
        this.thr = thr;
       setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
       this.setTitle("Remind");
       this.setLocation(450, 300);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taIonformation = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        taIonformation.setEditable(false);
        taIonformation.setColumns(20);
        taIonformation.setLineWrap(true);
        taIonformation.setRows(5);
        taIonformation.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taIonformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stop();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sound.suspend();
    }//GEN-LAST:event_formWindowClosing

   
    /**
     * Ham chay thong bao
     */
    public void action(){
        this.setVisible(true);
        sound.start();
    }
    
    
    public void stop(){
        //this.dispose();
        sound.suspend();
       
    }
    public void Show(String information){
        taIonformation.setText(information);
    }
    private Thread thr;
    private MakeSound sound ;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taIonformation;
    // End of variables declaration//GEN-END:variables
}
