/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_oop;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 * Class SpecialTask
 * Tao frame hien mot danh sach cac Task 
 * @author nhom2
 */
public class SpecialTask extends javax.swing.JFrame {

    /**
     * Creates new form SpecialTask
     */
    public SpecialTask() {
        initComponents();
    }

    /**
     * Ham khoi tao co tham so
     * @param tld Danh sach task
     */
    public SpecialTask(ArrayList<Task> tld) {
        initComponents();
        aL = tld;
        initData();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        information = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        information.setColumns(20);
        information.setLineWrap(true);
        information.setRows(5);
        information.setWrapStyleWord(true);
        jScrollPane2.setViewportView(information);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Xu ly su kien kich chuot vao mot Task trong list
     * @param evt su kien
     */
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        int noteSelect = jList1.getSelectedIndex();
        if(noteSelect >= 0) {
            information.setText(aL.get(noteSelect).showInformation(1));
        } 
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * Nap du lieu cho List
     */
     private void initData(){
        DefaultListModel model = new DefaultListModel();
        for(Task n : aL){
            model.addElement(n.getName());
        }
        jList1.setModel(model);
    }
   
     /**
      * Danh sach Task can hien thi
      */
     private ArrayList<Task> aL;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea information;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
